-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 20:33:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `customer_ID` INT NOT NULL,
  `customer_name` VARCHAR(50) NOT NULL,
  `customer_address` VARCHAR(100) NOT NULL,
  `customer_phone` VARCHAR(50) NOT NULL,
  `customer_email` VARCHAR(50) NOT NULL,
  `customer_DOB` DATE NOT NULL,
  PRIMARY KEY (`customer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Plan` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Plan` (
  `plan_ID` INT NOT NULL,
  `plan_type` VARCHAR(50) NOT NULL,
  `plan_name` VARCHAR(50) NOT NULL,
  `plan_duration` INT NOT NULL,
  `plan_cost` DECIMAL(10,2) NOT NULL,
  `plan_features` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`plan_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Transaction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Transaction` (
  `transaction_ID` INT NOT NULL,
  `customer_ID` INT NOT NULL,
  `plan_ID` INT NOT NULL,
  `transaction_type` VARCHAR(50) NOT NULL,
  `transaction_date` DATE NOT NULL,
  `transaction_amount` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`transaction_ID`),
  INDEX `customer_ID_idx` (`customer_ID` ASC) VISIBLE,
  INDEX `plan_ID_idx` (`plan_ID` ASC) VISIBLE,
  CONSTRAINT `customer_planfk_ID`
    FOREIGN KEY (`customer_ID`)
    REFERENCES `mydb`.`Customer` (`customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `plan_planfk_ID`
    FOREIGN KEY (`plan_ID`)
    REFERENCES `mydb`.`Plan` (`plan_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Call_traffic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Call_traffic` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Call_traffic` (
  `call_ID` INT NOT NULL,
  `call_date` DATE NOT NULL,
  `call_duration` INT NOT NULL,
  `call_cost` DECIMAL(10,2) NOT NULL,
  `call_type` VARCHAR(45) NOT NULL,
  `customer_ID` INT NOT NULL,
  PRIMARY KEY (`call_ID`),
  INDEX `customer_ID_idx` (`customer_ID` ASC) VISIBLE,
  CONSTRAINT `customer_traffic_ID`
    FOREIGN KEY (`customer_ID`)
    REFERENCES `mydb`.`Customer` (`customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_Plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer_Plan` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer_Plan` (
  `customer_ID` INT NOT NULL,
  `plan_ID` INT NOT NULL,
  PRIMARY KEY (`customer_ID`, `plan_ID`),
  INDEX `plan_ID_idx` (`plan_ID` ASC) VISIBLE,
  CONSTRAINT `customer_ID`
    FOREIGN KEY (`customer_ID`)
    REFERENCES `mydb`.`Customer` (`customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `plan_ID`
    FOREIGN KEY (`plan_ID`)
    REFERENCES `mydb`.`Plan` (`plan_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cancellation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cancellation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cancellation` (
  `cancellation_ID` INT NOT NULL,
  `customer_ID` INT NOT NULL,
  `cancellation_date` DATE NOT NULL,
  `cancellation_reason` VARCHAR(500) NULL,
  PRIMARY KEY (`cancellation_ID`),
  INDEX `customer_ID_idx` (`customer_ID` ASC) VISIBLE,
  CONSTRAINT `customer_cancellationfk_ID`
    FOREIGN KEY (`customer_ID`)
    REFERENCES `mydb`.`Customer` (`customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
